### ISSUE TITLE
Implement call to inner-gerbil

### ISSUE THREAD

**Issue by FrankDhondt** [dimitrydhondt/arty-gerbil#1]
Implement AngularJS service to easily call inner-gerbil API
See example in https://github.com/dimitrydhondt/elasjs/blob/master/public/elas/js/backend.js

**Comment by FrankDhondt** [comment]
sri4node only allows calls from heroku url
![inner-gerbil access-control-allow-origin problem](https://cloud.githubusercontent.com/assets/12109288/8238760/e8132c34-15f7-11e5-80e4-12ae725cd3c3.PNG)

**Comment by dimitrydhondt** [comment]
Can we close this ?
